#!/bin/sh
set -e
luajit test/oop_test.lua
files=$(find . -type f | rg \.lua$ | rg -v "src/components/fields/component_fields.lua")
stylua -c $files
bad=false
for file in $(echo $files | sed 's/ /\n/g' | rg "src" | rg -v "src/components/fields/special_component_fields.lua" | rg -v "src/components/fields/component_types.lua");
do
	first=$(head -n 1 < $file)
	if [ "$first" != "local require = require" ]; then
		echo "\033[31;1m$file\033[0m"
		bad=true
	fi
done
if [ "$bad" != false ]; then
	exit 1
fi
