#!/bin/sh
luajit test/oop_test.lua
stylua -c $(find . -type f | rg \.lua$)
for file in $(find src -type f | rg \.lua$);
do
	first=$(head -n 1 < $file)
	if [ "$first" != "local require = require" ]; then
		echo "\033[31;1m$file\033[0m"
		exit 1
	fi
done
